local fakeReportingService = {}

function fakeReportingService.ReportCounter() end
function fakeReportingService.ReportInfluxSeries() end
function fakeReportingService.ReportStats() end
function fakeReportingService.SetRBXEvent() end
function fakeReportingService.SetRBXEventStream() end
function fakeReportingService.TrackEvent() end
function fakeReportingService.UpdateHeartbeatObject() end
function fakeReportingService.ReleaseRBXEventStream() end

return fakeReportingService